# Generated by Django 5.2.4 on 2025-07-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="title",
            new_name="product_name",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="content",
        ),
        migrations.AddField(
            model_name="shop",
            name="price",
            field=models.CharField(default="exit", max_length=100),
            preserve_default=False,
        ),
    ]
