# Generated by Django 5.2.4 on 2025-07-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_category_shop_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Shop",
            new_name="Popular_product",
        ),
    ]
