# Generated by Django 5.2.4 on 2025-07-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_rename_shop_popular_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discounted_product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="shop")),
                ("price", models.CharField(max_length=100)),
                ("old_price", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.category",
                    ),
                ),
            ],
        ),
    ]
