# Generated by Django 5.2.4 on 2025-07-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_discounted_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
