# Generated by Django 5.2.4 on 2025-07-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
