# Generated by Django 5.2.4 on 2025-07-22 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discounted_product",
            name="image",
            field=models.ImageField(upload_to="discounted_product"),
        ),
        migrations.AlterField(
            model_name="popular_product",
            name="image",
            field=models.ImageField(upload_to="popular_product"),
        ),
        migrations.CreateModel(
            name="Smartfon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="shop")),
                ("price", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.category",
                    ),
                ),
            ],
        ),
    ]
