# Generated by Django 5.2.4 on 2025-07-23 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_discounted_product_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="popular_product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="smartfon",
            name="category",
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="product/images")),
                ("discount_price", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.category",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Discounted_product",
        ),
        migrations.DeleteModel(
            name="Popular_product",
        ),
        migrations.DeleteModel(
            name="Smartfon",
        ),
    ]
