# Generated by Django 5.2.4 on 2025-07-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_popular_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
    ]
