# Generated by Django 5.2.4 on 2025-07-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_product_is_popular"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
