# Generated by Django 5.2.4 on 2025-07-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
