# Generated by Django 5.2.4 on 2025-08-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_category_slug_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
